name: Build and Deploy Discord Dashboard

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Install Faraday Retry
        run: npm install faraday-retry
      - name: Build with Jekyll and Faraday Retry
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
          env:
            FAILED_REQUESTS_RETRY: 1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          artifact: _site
      - name: Run Discord Dashboard
        run: |
          cd Discord-Dashboard
          npm run start

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Vercel
        uses: vercel/vercel-plugin-github-actions@v1
        with:
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-api-token: ${{ secrets.VERCEL_API_TOKEN }}
          site-name: discord-dashboard
          deploy-branch: main
