name: Build and Deploy Discord Dashboard

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
           cd discord-dashboard
           npm install
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./index.js
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          artifact: _site
      - name: Run Discord Dashboard
        run: |
          cd discord-dashboard
          run: node index.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Vercel
        uses: vercel/vercel-plugin-github-actions@v1
        with:
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-api-token: ${{ secrets.VERCEL_API_TOKEN }}
          site-name: discord-dashboard
          deploy-branch: main
